// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVyGUMtC76XFnO1S4dBSjiKzzR0-E15ww',
    appId: '1:527081854620:web:c38880682dc71bdc6bbf59',
    messagingSenderId: '527081854620',
    projectId: 'chivero-c416b',
    authDomain: 'chivero-c416b.firebaseapp.com',
    storageBucket: 'chivero-c416b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBoMI-5IIYctZsqyXlWdxm3h7hsaDzC3Y',
    appId: '1:527081854620:android:4f75390a8a19cba26bbf59',
    messagingSenderId: '527081854620',
    projectId: 'chivero-c416b',
    storageBucket: 'chivero-c416b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPtlMPaa3z6CeQ48GF9E3fOqq8AVRKRUo',
    appId: '1:527081854620:ios:87672cc35d4448926bbf59',
    messagingSenderId: '527081854620',
    projectId: 'chivero-c416b',
    storageBucket: 'chivero-c416b.firebasestorage.app',
    iosBundleId: 'com.example.chivero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPtlMPaa3z6CeQ48GF9E3fOqq8AVRKRUo',
    appId: '1:527081854620:ios:87672cc35d4448926bbf59',
    messagingSenderId: '527081854620',
    projectId: 'chivero-c416b',
    storageBucket: 'chivero-c416b.firebasestorage.app',
    iosBundleId: 'com.example.chivero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVyGUMtC76XFnO1S4dBSjiKzzR0-E15ww',
    appId: '1:527081854620:web:7304dd64a27500ba6bbf59',
    messagingSenderId: '527081854620',
    projectId: 'chivero-c416b',
    authDomain: 'chivero-c416b.firebaseapp.com',
    storageBucket: 'chivero-c416b.firebasestorage.app',
  );

}