// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgxP_7sWXb2XgaiRO9CrSpJGPT8of5yA',
    appId: '1:579406671160:web:034e23d4ad87e1fd23a5cd',
    messagingSenderId: '579406671160',
    projectId: 'chivero-7278c',
    authDomain: 'chivero-7278c.firebaseapp.com',
    storageBucket: 'chivero-7278c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp5m4AhVQYVnMXaZVbvzQGlT0aKMpFW9s',
    appId: '1:579406671160:android:93874fc521625f4723a5cd',
    messagingSenderId: '579406671160',
    projectId: 'chivero-7278c',
    storageBucket: 'chivero-7278c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxZAm-AAUhLshbX23w2JZvi_7tffHkmPo',
    appId: '1:579406671160:ios:1160581a2525759623a5cd',
    messagingSenderId: '579406671160',
    projectId: 'chivero-7278c',
    storageBucket: 'chivero-7278c.firebasestorage.app',
    iosBundleId: 'com.example.chivero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxZAm-AAUhLshbX23w2JZvi_7tffHkmPo',
    appId: '1:579406671160:ios:1160581a2525759623a5cd',
    messagingSenderId: '579406671160',
    projectId: 'chivero-7278c',
    storageBucket: 'chivero-7278c.firebasestorage.app',
    iosBundleId: 'com.example.chivero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTgxP_7sWXb2XgaiRO9CrSpJGPT8of5yA',
    appId: '1:579406671160:web:ab45be0b2eae1fc523a5cd',
    messagingSenderId: '579406671160',
    projectId: 'chivero-7278c',
    authDomain: 'chivero-7278c.firebaseapp.com',
    storageBucket: 'chivero-7278c.firebasestorage.app',
  );

}